# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ed3e8d5fd3b953c9818f877910e82fcf98271db3a1979a5affcf21a02632284f71fa8ea4ce0db8b67ccaaa50701545f00eccb50c6eb94c972b5ada3a6f3ba6d

test:
  secret_key_base: 0e05bd4974005f59cb0ff223d05454e3cb2e64327b11cd3cf7613002b903b0279e317cc514e4312a863a7517a3676372fa2d67f610ba3924db8c235c2cfa0480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
